### ISSUE TITLE
Wrap a web component class directly

### ISSUE THREAD

**Issue by MathieuPuech** [BBKolton/reactify-wc#10]
Instead of passing the tagName to the reactifyWc function it could be nice if we can give the class of the component. The customeElements definition could be done in the function with an unique tag name to avoid side effects when using multiple version of a component in a page.

Creating a unique tag name could be done like it is in [@open-wc/scoped-elements](https://open-wc.org/scoped-elements/).

**Comment by BBKolton** [comment]
Hi @MathieuPuech, thank you for the suggestion! I think that's a great idea. I would like to not change the present API, but I think that the function could evaluate if the first passed property is a string or not, and then work from there. Feel free to open a PR with the change

**Comment by frank-dspeed** [comment]
I would say do not do that this could easy be a extra package if you apply such stuff that messes up my DOM implementation reactify gets useless you should not do such stuff.

This should be corrected on the bundler level for the final app that composes the components into a app

when you correct that on the component level in your component you can mess up everything that is not a react component.

ok thats it. If you want to go ahead with that you promote bad patterns stuff like static typings has got invented to detect such problems. 

You will also most time break browser integration tests anyway as my test will select the original name of the component.

You do not need extra places to register modules scoped and all that. there are round about at minimum 19 ways to instantiate a customElement without using customElement.define

for example look into that. https://dev.to/frankdspeed/the-html-component-pattern-hcp-3pkp

**Comment by brion-fuller** [comment]
I think this is ideally a lower level package.  Scoped elements are out of scope for this.
