### ISSUE TITLE
How can you provide <Props> type to component in Typescript?

### ISSUE THREAD

**Issue by BrianJVarley** [BBKolton/reactify-wc#15]
Hey @BBKolton, I'm using this package in a React TypeScript project, so far it's been helpful to bridge the gap converting from a Custom Element to React component.

But something I'm not clear on is how you provide a concrete `Props` type to the `reactifyWc('my-component')` call.
I did see a related PR here actually to provide the Props type - https://github.com/BBKolton/reactify-wc/issues/6. But in my example below the `name`, `age` props are not showing in _intellisense_ although I've provided them in the `Test` interface.

Could you provide some code examples of how you attach _Props_ to a component created with `reactifyWc`? 
I don't see any similar examples in the README.

Below is my attempt at attaching props and resulting outcome in intellisense:

***Creating Component Wrapper:***
```JavaScript
import reactifyWc from "reactify-wc";

interface Test {
  name: string;
  age: number;
}

export function createReactComponent(elementName: string) {
  return reactifyWc<Test>(elementName);
}
```

**Result in VsCode:**

Instead of picking up the `Test` type, the IDE is picking up the component's type as `'IntrinsicAttributes & RefAttributes<any>'` somehow.

<img width="563" alt="reactify-wc-prop-types-test" src="https://user-images.githubusercontent.com/6731968/94554942-bc05c280-0252-11eb-9b7b-3ee58bee6cdb.PNG">

```Bash
Type '{ name: any; age: any; }' is not assignable to type 'IntrinsicAttributes & RefAttributes<any>'.
  Property 'name' does not exist on type 'IntrinsicAttributes & RefAttributes<any>'.
```

**Comment by bardoo** [comment]
Added a PR to fix this: https://github.com/BBKolton/reactify-wc/pull/18

**Comment by brion-fuller** [comment]
This has been merged.  Can you check it out?

**Comment by Inoir** [comment]
Hey, i just tried to use this package with typescript, and it seems there is a bug again with passing Props. You still can pass them, but they are not on the types output.

<img width="597" alt="Screenshot 2021-10-29 at 09 09 48" src="https://user-images.githubusercontent.com/5294072/139391451-8b94e38c-7f93-4410-b92d-075a44651c88.png">

Output should be something like `ForwardRefExoticComponent<Props & RefAttributes>`.
