### ISSUE TITLE
Support older react versions

### ISSUE THREAD

**Issue by adamochayon** [BBKolton/reactify-wc#3]
The peer dependency specified by this package is `react@^16.9.0`, however I see no reason to not support earlier versions as well.
I believe `16.3.0` would be the first supported version (due to the reliance on `React.createRef`).

**Comment by BBKolton** [comment]
Sounds like a good idea, and quite reasonable. Would you be able to quickly verify that this will work as far back as `16.3.0`?

**Comment by adamochayon** [comment]
I'm not sure what your test environment is like for this repo, but I verified locally. I saw you have a test branch, maybe you should also run it there to make sure.

**Comment by BBKolton** [comment]
No testing yet sadly :(
I hope to get the testing completed and working soon, like within the next month or so. For now I'll include the older version number in the next update

**Comment by BBKolton** [comment]
Update now live in version 2.0.0!
