### ISSUE TITLE
Provide possibility to provide props type

### ISSUE THREAD

**Issue by Vlad160** [BBKolton/reactify-wc#6]
In current implementation:
```
return class extends Component {
    props: any;
```
It would be nice to have it like this:

```
const reactifyWebComponent = <Props = any>(WC: string) => {
  return class extends Component {
    props: Props;
```

It will add IntelliSense for typescript projects.

I can help with this if you want this feature

**Comment by BBKolton** [comment]
Hi Vlad, thanks for the suggestion! If you provide a PR I'll get on it ASAP and can promise a release by EOD Sunday?

**Comment by Vlad160** [comment]
Hi Bryce! I will create it today

**Comment by BrianJVarley** [comment]
Hi @Vlad160 I opened a new issue related to your PR on props type. Can you give some example of how the <Props> type should be passed into the reactifyWC call? - https://github.com/BBKolton/reactify-wc/issues/15

**Comment by Vlad160** [comment]
Hi @BrianJVarley ! My PR was for version 2.0.2 and it worked. Checked my version and it works for 
```
const SearchInput = reactifyWc<{open: boolean}>('wc-search-input');
```

Can you check this version?

**Comment by BrianJVarley** [comment]
@Vlad160 I'm using the latest version, so it should contain your PR changes? - `"reactify-wc": "^4.0.0"`

I've tested here with your above Props example, but the generated index.d.ts file doesn't contain the type with `open` prop:

```
return reactifyWc<{ open: boolean }>(elementName);
```

The generated `d.ts` file doesn't contain the above prop type. Instead it contains a signature of the following.

![image](https://user-images.githubusercontent.com/6731968/94714587-3eba7a80-0344-11eb-84dc-c5beb270b422.png)

Which is the default return type of reactifyWc if I hover over it in VsCode:

![image](https://user-images.githubusercontent.com/6731968/94714801-8c36e780-0344-11eb-8105-a3137f733fbf.png)

Any ideas why the generated index.d.ts file isn't picking up this new Type prop?
