### ISSUE TITLE
Cannot pass styles to web component

### ISSUE THREAD

**Issue by leifriksheim** [BBKolton/reactify-wc#8]
Hi. Thanks for this package. It seems like I cannot pass style props like an object to the custom element after converting to a React component.

**Comment by BBKolton** [comment]
Hi @leifriksheim, thanks for the issue report! React has its own syntax for styling that is semantically different from the browser. There are many options out there for more detailed and less-ugly styling than inline objects that should work well with a reactified component. However, I definitely see the merit of supporting the style syntax. 

Please feel free to take a stab at it and open a PR!
