### ISSUE TITLE
Cannot override default boolean value TRUE because FALSE props are removed

### ISSUE THREAD

**Issue by MagnusPoppe** [BBKolton/reactify-wc#9]
https://github.com/BBKolton/reactify-wc/blob/772c99aceee3581f2b6e38be1904f021fae88f79/src/index.ts#L38-L48

If a default value is set to be `true` for a web-component, the value will always be `true` due to `false` values being deleted.

**Comment by BBKolton** [comment]
Hi @MagnusPoppe, thank you for the issue! This is one of those strange intersections of browser handling and React handling things differently. AFAIK, the browser spec does indeed recommend "false" attributes to be not present at all. 

However, in the latest release, I spent some time with the help of @nathfisher adding forced typings. You can now directly set a boolean as a property if you want. Please take a look at the README to see how to use it, or checkout the new tests folder.
